### ISSUE TITLE
Take keyboard input for triangle movement

### ISSUE THREAD

**Issue by jimbo00000** [DanielMGessel/BostonLinux-Graphics#1]
Move the triangle left and right by pressing and holding the arrow keys. Bound the triangle's movement to the bottom 1/3 or 1/4 of the canvas.

**Comment by BrianJLevine** [comment]
I added the handlers for left and right arrow and space bar.  And the ship now moves (have to click inside the canvas before pressing keys or it won't work).  Not sure what you meant about binding the triangle's movement...  Oh yeah and the ship will move out of view.  The X coordinate of the ship can go from -20 to 20.  I think the matrix transforms might change those X values and since I'm new to this I decided not to muck it up.

**Comment by DanielMGessel** [comment]
Cool! I’ve been focused on a few other things - should get to this by the weekend.

Dan

**Comment by jimbo00000** [comment]
By "bound" I meant enforce a bound on the values the variable can have - in our case [-19,19] on x to ensure the triangle stays visible in the canvas. Right now the ship has no vertical movement - maybe I was thinking of a different game.
